version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        environment:
            - APACHE_DOCUMENT_ROOT=/var/www/html/public
        networks:
            - laravel_net

networks:
    laravel_net:
